# Generated by Django 5.0.4 on 2024-04-20 23:30

import artista.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[artista.models.validar_cpf])),
                ('tipo_chave_pix', models.CharField(choices=[('cel', 'Celular'), ('cnpj', 'CNPJ'), ('email', 'E-mail')], default='cel', max_length=10)),
                ('chave_pix', models.CharField(max_length=100)),
            ],
        ),
    ]
