# Generated by Django 5.0.4 on 2024-04-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0003_remove_artista_created_at_remove_artista_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='banco',
            field=models.CharField(default='Banco Padrão', max_length=100),
        ),
        migrations.AddField(
            model_name='artista',
            name='telefone',
            field=models.CharField(default='Telefone Padrão', max_length=15),
        ),
        migrations.AlterField(
            model_name='artista',
            name='tipo_chave_pix',
            field=models.CharField(choices=[('cel', 'Celular'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('cpf', 'CPF')], default='cel', max_length=10),
        ),
    ]
