# Generated by Django 5.0.4 on 2024-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0004_artista_banco_artista_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='banco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
