# Generated by Django 5.0.4 on 2024-04-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0005_alter_artista_banco_alter_artista_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artista.artista')),
            ],
        ),
    ]
